project:
  name: quickstart-sumo-logic-cloudsiem/2
  shorten_stack_name: true
  s3_regional_buckets: true
  regions:
    - us-east-2
  artifact_regions:
    - us-east-2
tests:
  default:
    template: ./templates/main-org.template.yaml
    regions:
    - us-east-2
    parameters:
      QSS3KeyPrefix: "quickstart-sumo-logic-cloudsiem/"
      QSS3BucketName:  "$[taskcat_autobucket_prefix]"
      QSS3BucketRegion: "us-east-2"
      QSVersion: "2"
      # Section1SumoLogicDeployment: "us1"
      # Section1SumoLogicAccessID: ""
      # Section1SumoLogicAccessKey: ""
      # Section1SumoLogicOrganizationId: ""
      Section1SecurityToolingAccountId: ""
      Section1ToolingAndLoggingRegion: "us-east-2"
      Section1LogArchivingAccountId: ""
      Section1OrganizationRootID: ""
      Section1DeliveryBucketPrefix: logs-delivery

      Section2InstallSumoGlobalGuardDutyApp: "No"
      Section2InstallSumoCloudSecurityMonitoringandAnalyticsGuardDutyApp: "Yes"
      Section2GuardDutyRegions: "us-east-2"
      Section2AdditionalConfigurationFeatures: "MalwareProtection,S3Logs"
      Section2GuardDutyCreateHttpLogsSource: "Yes"
      
      Section3CloudTrailRegion: "us-east-2"
      Section3EnableAWSCloudTrail: "Yes"
      Section3InstallPCICloudTrailApp: "No"
      Section3InstallCISFoundationApp: "No"
      Section3InstallCloudTrailMonitoringAnalyticsApp: "Yes"
      Section3InstallCloudTrailSecOpsApp: "No"
      Section3CloudTrailCreateS3LogsSource: "Yes"
      Section3CreateCloudTrailS3Bucket: "Yes"
      Section3DisassociateAdminAccountOnDeleteStack: "false"
      
      Section4SecurityHubEnableSecurityHub: "Yes"
      Section4SecurityHubRegionLinkingMode: "SPECIFIED_REGIONS"
      Section4SecurityHubLinkedRegions: "us-east-2,us-west-1"
      Section4SecurityHubInstallSumoSecurityHubCloudSecurityMonitoringandAnalyticsApp: "Yes"
      Section4SecurityHubRegionsToEnable: "us-east-2,us-west-1"
      Section4SecurityHubCreateHttpLogsSource: "Yes"

      Section6EnableFirewallManager: "Yes"
      Section6DisassociateAdminAccountOnDeleteStack: "false"
      Section6InstallSumoAWSWAFCloudSecurityMonitoringAndAnalyticsApp: "Yes"
      Section6InstallSumoAWSNetworkFirewallApp: "No"
      Section6FirewallManagerPolicyRegions: "us-east-2"
      Section6CreateDeliveryStreamSource: "Yes"
      Section6DeliveryStreamName: $[taskcat_random-string]
      Section6CreateS3Source: "Yes"
      Section6CreateS3Bucket: "Yes"
      Section6DeliveryBucketPrefix: nw-logs-delivery
      
