project:
  name: cfn-ps-sumo-logic-cloudsiem/2
  shorten_stack_name: true
  s3_regional_buckets: true
  regions:
    - us-east-2
  artifact_regions:
    - us-east-2
tests:
  default:
    template: ./templates/main-org.template.yaml
    regions:
    - us-east-2
    parameters:
      QSS3KeyPrefix: "cfn-ps-sumo-logic-cloudsiem/"
      QSS3BucketName:  "$[taskcat_autobucket_prefix]"
      QSS3BucketRegion: "us-east-2"
      QSVersion: "2"
      # Section1SumoLogicDeployment: "us1"
      # Section1SumoLogicAccessID: ""
      # Section1SumoLogicAccessKey: ""
      # Section1SumoLogicOrganizationId: ""
      Section1SecurityToolingAccountId: ""
      Section1ToolingAndLoggingRegion: "us-east-2"
      Section1LogArchivingAccountId: ""
      Section1OrganizationRootID: ""
      Section1DeliveryBucketPrefix: logs-delivery
      Section1SumoLogicResourceRemoveOnDeleteStack: "true"

      Section2InstallSumoGlobalGuardDutyApp: "Yes"
      Section2InstallSumoCloudSecurityMonitoringandAnalyticsGuardDutyApp: "Yes"
      Section2GuardDutyRegions: "us-east-2"
      Section2AdditionalConfigurationFeatures: "MalwareProtection,S3Logs"
      Section2GuardDutyCreateHttpLogsSource: "Yes"
      Section2GuardDutyHttpLogsSourceCategoryName: "aws/quickstart/guardduty/logs"

      Section3CloudTrailRegion: "us-east-2"
      Section3EnableAWSCloudTrail: "Yes"
      Section3InstallPCICloudTrailApp: "Yes"
      Section3InstallCISFoundationApp: "Yes"
      Section3InstallCloudTrailMonitoringAnalyticsApp: "Yes"
      Section3InstallCloudTrailSecOpsApp: "Yes"
      Section3CloudTrailCreateS3LogsSource: "Yes"
      Section3CreateCloudTrailS3Bucket: "Yes"
      Section3DisassociateAdminAccountOnDeleteStack: "false"
      Section3CloudTrailLogsSourceCategoryName: "aws/quickstart/cloudtrail/logs"
      Section3CloudTrailBucketPathExpression: "CloudTrail/AWSLogs/*"
      
      Section4SecurityHubEnableSecurityHub: "Yes"
      Section4SecurityHubRegionLinkingMode: "SPECIFIED_REGIONS"
      Section4SecurityHubLinkedRegions: "us-east-2"
      Section4SecurityHubInstallSumoSecurityHubCloudSecurityMonitoringandAnalyticsApp: "Yes"
      Section4SecurityHubRegionsToEnable: "us-east-2"
      Section4SecurityHubCreateHttpLogsSource: "Yes"
      Section4SecurityHubHttpLogsSourceCategoryName: "aws/quickstart/securityhub/logs"
      Section2FindingPublishingFrequency: "FIFTEEN_MINUTES"
      Section4SecurityHubEnableCISStandard: "true"
      Section4SecurityHubEnablePCIStandard: "true"
      Section4SecurityHubEnableSBPStandard: "true"

      Section6EnableFirewallManager: "Yes"
      Section6DisassociateAdminAccountOnDeleteStack: "false"
      Section6InstallSumoAWSWAFCloudSecurityMonitoringAndAnalyticsApp: "Yes"
      Section6InstallSumoAWSNetworkFirewallApp: "Yes"
      Section6FirewallManagerPolicyRegions: "us-east-2"
      Section6CreateDeliveryStreamSource: "Yes"
      Section6DeliveryStreamName: sumologic-kinesis-$[taskcat_random-string]
      Section6CreateS3Source: "Yes"
      Section6CreateS3Bucket: "Yes"
      Section6DeliveryBucketPrefix: nw-logs-delivery
      Section6S3SourceCategoryName: "aws/quickstart/nfw/logs"
      Section6DeliveryStreamSourceCategoryName: "aws/quickstart/waf/logs"
      Section6CreateVpcForSG: "true"
      
