project:
  name: cfn-ps-sumo-logic-cloudsiem
  shorten_stack_name: true
  s3_regional_buckets: true
  regions:
    - us-east-2
  artifact_regions:
    - us-east-2
tests:
  default:
    template: ./templates/main-org.template.yaml
    regions:
    - us-east-2
    parameters:
      QSS3KeyPrefix: "quickstart-sumo-logic-cloudsiem/"
      QSS3BucketName:  "$[taskcat_autobucket_prefix]"
      QSS3BucketRegion: "us-east-2"
      # Section1SumoLogicDeployment: "us1"
      # Section1SumoLogicAccessID: ""
      # Section1SumoLogicAccessKey: ""
      # Section1SumoLogicOrganizationId: ""
      Section1SecurityToolingAccountId: ""
      Section1ToolingAndLoggingRegion: "us-east-2"
      Section1LogArchivingAccountId: ""
      Section1OrganizationRootID: ""
      Section1DeliveryBucketPrefix: logs-delivery-$[taskcat_random-string]
      Section2InstallSumoGlobalGuardDutyApp: "Yes"
      Section2InstallSumoCloudSecurityMonitoringandAnalyticsGuardDutyApp: "No"
      Section2GuardDutyRegions: "us-east-2"
      Section2GuardDutyCreateHttpLogsSource: "Yes"
      Section3CloudTrailRegions: "us-east-2"
      Section3InstallAWSCloudTrail: "Yes"
      Section3InstallPCICloudTrailApp: "Yes"
      Section3InstallCISFoundationApp: "Yes"
      Section3InstallCloudTrailMonitoringAnalyticsApp: "Yes"
      Section3InstallCloudTrailSecOpsApp: "Yes"
      Section3CloudTrailCreateS3LogsSource: "Yes"
      Section3CreateCloudTrailS3Bucket: "Yes"

      Section4SecurityHubEnableSecurityHub: "Yes"
      Section4SecurityHubInstallSumoSecurityHubCloudSecurityMonitoringandAnalyticsApp: "Yes"
      Section4SecurityHubRegionsToEnable: "us-east-2"
      Section4SecurityHubCreateHttpLogsSource: "Yes"

      Section6EnableFirewallManager: "Yes"
      Section6DisassociateAdminAccountOnDeleteStack: "false"
      Section6InstallSumoAWSWAFCloudSecurityMonitoringAndAnalyticsApp: "Yes"
      Section6InstallSumoAWSNetworkFirewallApp: "Yes"
      Section6FirewallManagerPolicyRegions: "us-east-2"
      Section6CreateDeliveryStreamSource: "Yes"
      Section6DeliveryStreamName: $[taskcat_random-string]
      Section6CreateS3Source: "Yes"
      Section6CreateS3Bucket: "Yes"
      Section6DeliveryBucketPrefix: nw-logs-delivery-$[taskcat_random-string]
      
